### ISSUE TITLE
Fire Tracker: Fix style related issues in Internet Explorer

### ISSUE THREAD

**Issue by jo-im** [SCPR/firetracker#217]
KPCC + Laist logos are cut off at the bottom.
![Screen Shot 2018-09-19 at 12.30.40 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/d829b501-4d05-43c8-a53c-23db0d44bf49)

Background color of fire list should be a dark grey which could be the reason why the outline of fire titles are odd and the California Fire Resources cannot be seen.
![Screen Shot 2018-09-19 at 12.19.46 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/fe4839b5-c915-4d56-b042-ee1c4ca10e6d)

Fire details and icons in header do not show up in IE.
![Screen Shot 2018-09-19 at 12.35.36 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/2253928f-130e-454c-a561-9fcc962cf533)

AC: 
- [ ] The KPCC + Laist logos are no longer cut off at the bottom
- [ ] Background color of the fire list should be a dark grey
- [ ] California Fire Resources are visible
- [ ] Make fire details and icons in header visible
