### ISSUE TITLE
Fire Tracker needs archived data

### ISSUE THREAD

**Issue by chrislkeller** [SCPR/firetracker#62]
Could scrape or hard-code, though in doing that latter I'd need to gather all of the data anyway, so… scrapers gonna scrape - http://cdfdata.fire.ca.gov/incidents/incidents_archived?pc=500&archive_year=2012
- [x] Available data for 2012
- [ ] Available data for 2011
- [ ] Available data for 2010
- [ ] Available data for 2009
- [ ] Available data for 2008
- [ ] Available data for 2007
- [ ] Available data for 2006
- [ ] Available data for 2005
- [ ] Available data for 2004
- [ ] Available data for 2003
- [ ] Available data for 2002
- [ ] Available data for 2001
- [ ] Available data for 2000
- [ ] Available data for 1999
